# Generated by Django 2.1.15 on 2021-01-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setName', models.CharField(max_length=200)),
                ('question', models.CharField(max_length=2000)),
                ('answer', models.CharField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='Set',
        ),
    ]
