# Generated by Django 2.1.15 on 2021-01-26 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210126_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='setName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Set'),
        ),
        migrations.AddField(
            model_name='set',
            name='subjectName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Subject'),
        ),
    ]
