# Generated by Django 2.1.15 on 2021-01-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210126_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=2000),
        ),
    ]
